Remove custom mkshrc.
We don't use BusyBox, which is what this was originally for.

error: overriding commands for target
`/home/nexus/DU-CAF/target/product/oneplus3/system/etc/mkshrc',
previously defined at build/make/core/base_rules.mk:484

Change-Id: I25de3564be2c479afa1b8cb4eaf89ba2db9b4997